version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: frontend-container
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

  frontend-nginx:
    image: nginx:1.23-alpine
    container_name: frontend-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/usr/share/nginx/html 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/archive/livflow.co.kr/fullchain2.pem:/etc/letsencrypt/live/livflow.co.kr/fullchain.pem
      - /etc/letsencrypt/archive/livflow.co.kr/privkey2.pem:/etc/letsencrypt/live/livflow.co.kr/privkey.pem
      - ./certbot:/var/www/certbot
