name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Frontend to Server
    runs-on: ubuntu-latest

    env:
      PROJECT_DIR: /home/joo/front-end-coffee  # 서버에 배포될 프론트엔드 경로

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js 설정
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. 종속성 설치
      - name: Install dependencies
        run: |
          npm install

      # ✅ 4. 환경 변수 설정 및 빌드
      - name: Build project with environment variables
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_GOOGLE_REDIRECT_URI: ${{ secrets.VITE_GOOGLE_REDIRECT_URI }}
          VITE_GOOGLE_SCOPE: ${{ secrets.VITE_GOOGLE_SCOPE }}
          # VITE_KAKAO_CLIENT_ID: ${{ secrets.VITE_KAKAO_CLIENT_ID }}
          # VITE_KAKAO_REDIRECT_URI: ${{ secrets.VITE_KAKAO_REDIRECT_URI }}
          # VITE_NAVER_CLIENT_ID: ${{ secrets.VITE_NAVER_CLIENT_ID }}
          # VITE_NAVER_CLIENT_SECRET: ${{ secrets.VITE_NAVER_CLIENT_SECRET }}
          # VITE_NAVER_REDIRECT_URI: ${{ secrets.VITE_NAVER_REDIRECT_URI }}
        run: |
          npm run build

      # 5. 서버에 배포 (SSH 접속)
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/joo/Front-end-coffee
            git config pull.rebase false
            git pull origin main
            
            # 기존 볼륨과 컨테이너 제거 후 재시작
            echo ${{ secrets.SUDO_PASSWORD }} | sudo -S docker-compose down -v
            echo ${{ secrets.SUDO_PASSWORD }} | sudo -S docker-compose up -d --build
            
            # public 디렉터리 생성 및 파일 복사
            echo ${{ secrets.SUDO_PASSWORD }} | sudo -S docker exec frontend-nginx /bin/sh -c "
              mkdir -p /usr/share/nginx/html/public && 
              cp /usr/share/nginx/html/*.svg /usr/share/nginx/html/public/
            "

      # 6. Nginx 서비스 재시작
      - name: Restart Nginx
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/joo/Front-end-coffee
            echo ${{ secrets.SUDO_PASSWORD }} | sudo -S docker-compose restart frontend-nginx
